### ISSUE TITLE
Add legal requirement for receipt attachment

### ISSUE THREAD

**Issue by rammt** [dotkom/receipt-form#39]
Requirements for legal receipt:
- Date and time
- Description (what you buy)
- Company name (seller)
- Organization number (seller)
- VAT specification

Source: https://lovdata.no/dokument/SF/forskrift/2004-12-01-1558/KAPITTEL_5-1#§5-1-1

**Comment by oleast** [comment]
Thank you for specifying thing!

I had a little talk with a few other people in Bankom, and they formulated a small text to let people know they need a valid receipt.
